#! /usr/bin/python3
from sys import argv
import subprocess

interface = ''


def mon_check():
    realmonitor = False
    a = subprocess.run(['iwconfig', interface], capture_output=True, check=True, text=True).stdout.split()
    for i in a:
        if i[:5] == 'Mode:':
            if i[5:] == 'Monitor':
                realmonitor = True
    return realmonitor


def main():
    if subprocess.run(['whoami'], capture_output=True, text=True).stdout != 'root\n':
        print('Run it as root!')
        return 1

    global interface
    mode = None
    if len(argv) == 1:
        subprocess.run(['airmon-ng'])
        return 0
    elif len(argv) == 2:
        mode = argv[1]
    elif len(argv) == 3:
        mode = argv[1]
        interface = argv[2]
    else:
        print("wrong arg")
        return 228

    if mode == "check":
        subprocess.run(['airmon-ng', mode, interface])
        return 0

    monitor = False
    if interface[-3:] == "mon":
        monitor = True
    mon = mon_check()

    if mode == "start":
        if not monitor and not mon:
            subprocess.run(['ip', 'link', 'set', interface, 'down'])
            subprocess.run(['iw', 'dev', interface, 'set', 'type', 'monitor'])
            subprocess.run(['ip', 'link', 'set', interface, 'name', interface + 'mon'])
            interface += "mon"
            subprocess.run(['ip', 'link', 'set', interface, 'up'])
        elif monitor and not mon:
            subprocess.run(['ip', 'link', 'set', interface, 'down'])
            subprocess.run(['iw', 'dev', interface, 'set', 'type', 'monitor'])
            subprocess.run(['ip', 'link', 'set', interface, 'up'])
        elif not monitor and mon:
            subprocess.run(['ip', 'link', 'set', interface, 'down'])
            subprocess.run(['ip', 'link', 'set', interface, 'name', interface + 'mon'])
            interface += "mon"
            subprocess.run(['ip', 'link', 'set', interface, 'up'])
        if not mon_check():
            subprocess.run(['ip', 'link', 'set', interface, 'down'])
            subprocess.run(['iw', 'dev', interface, 'set', 'type', 'managed'])
            subprocess.run(['ip', 'link', 'set', interface, 'name', interface[:-3]])
            interface = interface[:-3]
            subprocess.run(['ip', 'link', 'set', interface, 'up'])
            print("denied, renaming interface")
            return 1
        return 0
    elif mode == "stop":
        if monitor and mon:
            subprocess.run(['ip', 'link', 'set', interface, 'down'])
            subprocess.run(['iw', 'dev', interface, 'set', 'type', 'managed'])
            subprocess.run(['ip', 'link', 'set', interface, 'name', interface[:-3]])
            interface = interface[:-3]
            subprocess.run(['ip', 'link', 'set', interface, 'up'])
        elif monitor and not mon:
            subprocess.run(['ip', 'link', 'set', interface, 'down'])
            subprocess.run(['ip', 'link', 'set', interface, 'name', interface[:-3]])
            interface += interface[:-3]
            subprocess.run(['ip', 'link', 'set', interface, 'up'])
        elif not monitor and monitor:
            subprocess.run(['ip', 'link', 'set', interface, 'down'])
            subprocess.run(['iw', 'dev', interface, 'set', 'type', 'managed'])
            subprocess.run(['ip', 'link', 'set', interface, 'up'])
        else:
            return 2
        return 0


if __name__ == '__main__':
    main()
